### PR TITLE
Fix compile time issues

### LINKED ISSUE #3179: Version 5.9.0 will not build as x86 system
By building collect 5.9.0 with cross-compiling (Buildroot), it works for an x86_64 system.
But when i try this for an x86 system i will get during the build the following faults:
src/daemon/plugin.c: In function 'plugin_init_all':
src/daemon/plugin.c:838:34: error: '%llu' directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Werror=format-truncation=]
     snprintf(name, sizeof(name), "writer#%" PRIu64,
                                  ^~~~~~~~~~
src/daemon/plugin.c:838:42: note: format string is defined here
     snprintf(name, sizeof(name), "writer#%" PRIu64,
src/daemon/plugin.c:838:34: note: directive argument in the range [0, 4294967295]
     snprintf(name, sizeof(name), "writer#%" PRIu64,
                                  ^~~~~~~~~~
src/daemon/plugin.c:838:5: note: 'snprintf' output between 9 and 18 bytes into a destination of size 16
     snprintf(name, sizeof(name), "writer#%" PRIu64,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              (uint64_t)write_threads_num);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/daemon/plugin.c:649:34: error: '%llu' directive output may be truncated writing between 1 and 10 bytes into a region of size 9 [-Werror=format-truncation=]
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
                                  ^~~~~~~~~~
src/daemon/plugin.c:649:42: note: format string is defined here
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
src/daemon/plugin.c:649:34: note: directive argument in the range [0, 4294967295]
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
                                  ^~~~~~~~~~
src/daemon/plugin.c:649:5: note: 'snprintf' output between 9 and 18 bytes into a destination of size 16
     snprintf(name, sizeof(name), "reader#%" PRIu64, (uint64_t)read_threads_num);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I suggest that this problem come up as by the src/daemon/plugin.c now will be set some parts for pure x86_64 system (PRIu64; unit64_t) and they will be not available as x86 system.

Best regards,
Roland Franke

### LINKED ISSUE #3242: RDT compile issue
*   Version of collectd: 5.9.1

## Expected behavior
compiles fine

## Actual behavior

```
  CCLD     hugepages.la
  CC       src/intel_rdt_la-intel_rdt.lo
In file included from src/utils/common/common.h:33,
                 from src/intel_rdt.c:32:
In function ‘strlisttoarray’,
    inlined from ‘oconfig_to_ngroups’ at src/intel_rdt.c:424:11,
    inlined from ‘rdt_config_ngroups’ at src/intel_rdt.c:516:7,
    inlined from ‘rdt_config’ at src/intel_rdt.c:1149:16,
    inlined from ‘rdt_config’ at src/intel_rdt.c:1100:12:
./src/daemon/plugin.h:394:20: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  394 | #define ERROR(...) plugin_log(LOG_ERR, __VA_ARGS__)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/intel_rdt.c:328:7: note: in expansion of macro ‘ERROR’
  328 |       ERROR(RDT_PLUGIN ": Duplicated process name \'%s\' in group \'%s\'",
      |       ^~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:7116: src/intel_rdt_la-intel_rdt.lo] Error 1
make[1]: Leaving directory '/home/mrunge/work/collectd'
make: *** [Makefile:4892: all] Error 2
```

## Steps to reproduce

*  Use master branch
*  ./configure --enable-intel-rdt
*   make

### PR DESCRIPTION
**Pull request by mrunge**
ChangeLog: Build System: fix compile time issues

This resolves #3242 and should also resolve #3179.

Signed-off-by: Matthias Runge <mrunge@redhat.com>

### CODE REVIEW

File: src/intel_rdt.c [hunk 1]
```diff
@@ -325,8 +325,12 @@ static int strlisttoarray(char *str_list, char ***names, size_t *names_num) {
       continue;
 
     if ((isdupstr((const char **)*names, *names_num, token))) {
-      ERROR(RDT_PLUGIN ": Duplicated process name \'%s\' in group \'%s\'",
-            token, str_list);
+      if (str_list != NULL)
```
Comment (anaudx) [inline src/intel_rdt.c]: I think you can simplify this by removing the `if (str_list != NULL)` statement and just leave the last line `ERROR(RDT_PLUGIN ": Duplicated process name \'%s\'", token);`, because the expression `str_list != NULL` will never be true after line 319 (`str_list = NULL;`). But your code works, so it's up to you. How do you think?

Comment (mrunge) [reply src/intel_rdt.c]: Yes, that was what I was thinking. I'll change the PR to match our common understanding. RDT is not my code, that I why I was looking for your feedback here.
