### PR TITLE
Turbostat Plugin - Add config boolean for logical CPU naming

### LINKED ISSUE #1974: turbostat plugin "coreNN" values stomping on each other on multi-socket systems
-   Version of collectd: 5.5.2 and 5.6.0
-   Operating system / distribution: CentOS 6.5 and 7.2
## Expected behavior

Unique per "core" IDs for the "per core" statistics (c3/c6/c7/temperature).
## Actual behavior

The "core id" for each CPU is non-unique across multi-socket systems (IE, core 1 is always core 1, whether it's on socket 0 or socket 1
## Steps to reproduce
-   Run turbostat plugin on multi-socket Intel system

The below snippet will illustrate the issue pretty well when run on a multi-socket system:

```
--- a/src/turbostat.c
+++ b/src/turbostat.c
@@ -553,6 +553,9 @@ submit_counters(struct thread_data *t, struct core_data *c, struct pkg_data *p)

        interval_float = CDTIME_T_TO_DOUBLE(time_delta);

+       WARNING("turbostat plugin: submit stats for cpu: %d, core: %d, pkg: %d",
+               t->cpu_id, c->core_id, p->package_id);
+
```

Output:

```
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 0, core: 0, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 1, core: 1, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 2, core: 2, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 3, core: 3, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 4, core: 4, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 5, core: 5, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 6, core: 6, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 7, core: 8, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 8, core: 9, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 9, core: 10, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 10, core: 11, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 11, core: 12, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 12, core: 13, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 13, core: 14, pkg: 0
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 14, core: 0, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 15, core: 1, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 16, core: 2, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 17, core: 3, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 18, core: 4, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 19, core: 5, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 20, core: 6, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 21, core: 8, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 22, core: 9, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 23, core: 10, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 24, core: 11, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 25, core: 12, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 26, core: 13, pkg: 1
Oct  4 13:58:38 localhost collectd[16753]: turbostat plugin: submit stats for cpu: 27, core: 14, pkg: 1
```

Proposed Fix:

Just keep using the CPU ids for per core statistics instead of using core IDs:

```
diff --git a/src/turbostat.c b/src/turbostat.c
index fc1b5dc..1054ad2 100644
--- a/src/turbostat.c
+++ b/src/turbostat.c
@@ -576,8 +576,6 @@ submit_counters(struct thread_data *t, struct core_data *c, struct pkg_data *p)
        if (!(t->flags & CPU_IS_FIRST_THREAD_IN_CORE))
                goto done;

-       ssnprintf(name, sizeof(name), "core%02d", c->core_id);
-
        if (do_core_cstate & (1 << 3))
                turbostat_submit(name, "percent", "c3", 100.0 * c->c3/t->tsc);
        if (do_core_cstate & (1 << 6))
```

### PR DESCRIPTION
**Pull request by brockcj**
Added boolean and updated documentation to reflect new config option. 
Fixes #1974

### CODE REVIEW

File: src/turbostat.c [hunk 1]
```diff
@@ -1566,6 +1578,8 @@ turbostat_config(const char *key, const char *value)
 	} else if (strcasecmp("PackageThermalManagement", key) == 0) {
 		config_ptm = IS_TRUE(value);
 		apply_config_ptm = 1;
+	} else if (strcasecmp("LogicalCoreNames", key) == 0) {
+		config_lcn = 1;
```
Comment (octo) [inline src/turbostat.c]: This does not behave in the way it is documented: setting `LogicalCoreNames false` will also *enable* the feature, because the argument to the option is not considered. Please use `config_lcn = IS_TRUE(value)` as above.

File: src/collectd.conf.pod [hunk 2]
```diff
@@ -7512,6 +7512,13 @@ should only be used if the automated detection fails or if you want to
 disable some collections. The different bits of this bitmask accepted
 by this plugin are:
 
+=item B<LogicalCoreNames> I<true>|I<false>
+
+Boolean enabling the use of logical core numbering for per core 
+statistics. This mirrors the in-kernel per core numbering. On
+multi-socket systems, the original per-cpu numbering behavior
+stomps on values on subsequent sockets.
+
```
Comment (octo) [inline src/collectd.conf.pod]: Please document what changes from the user's point of view. Something along the lines:

> When enabled, `cpu<n>` is used as *plugin instance*, where *n* is a sequential number assigned by the kernel. Otherwise, `core<n>` is used where *n* is the n-th core of the socket, causing name conflicts when there is more than one socket.

**Comment by brockcj** [comment]
Hi @octo Certainly. I've updated the PR with the changes.

**Comment by octo** [comment]
Thanks @brockcj!

File: src/collectd.conf.pod [hunk 3]
```diff
@@ -7512,6 +7512,14 @@ should only be used if the automated detection fails or if you want to
 disable some collections. The different bits of this bitmask accepted
 by this plugin are:
 
+=item B<LogicalCoreNames> I<true>|I<false>
```
Comment (Feandil) [inline src/collectd.conf.pod]: Please rename it to ```LogicalCPUNames``` (or something similar)

File: src/collectd.conf.pod [hunk 4]
```diff
@@ -7512,6 +7512,14 @@ should only be used if the automated detection fails or if you want to
...
+
+Boolean enabling the use of logical core numbering for per core
```
Comment (Feandil) [inline src/collectd.conf.pod]: ```logical processor numbering```

File: src/collectd.conf.pod [hunk 5]
```diff
@@ -7512,6 +7512,14 @@ should only be used if the automated detection fails or if you want to
 disable some collections. The different bits of this bitmask accepted
 by this plugin are:
 
+=item B<LogicalCoreNames> I<true>|I<false>
+
+Boolean enabling the use of logical core numbering for per core 
+statistics. When enabled, cpu<n> is used as plugin instance, where n
+is a sequential number assigned by the kernel. Otherwise, core<n> is
```
Comment (Feandil) [inline src/collectd.conf.pod]: I think we should be using ```pkg<n>-core<m>``` in the other case

File: src/turbostat.c [hunk 6]
```diff
@@ -65,6 +65,11 @@
 static _Bool aperf_mperf_unstable;
 
 /*
+ * If set, use kernel logical core numbering for all "per core" metrics.
```
Comment (Feandil) [inline src/turbostat.c]: ```logical processor numbering```

Why is there ```"``` around the ```per core```?

File: src/turbostat.c [hunk 7]
```diff
@@ -574,7 +583,10 @@ submit_counters(struct thread_data *t, struct core_data *c, struct pkg_data *p)
 	if (!(t->flags & CPU_IS_FIRST_THREAD_IN_CORE))
 		goto done;
 
-	ssnprintf(name, sizeof(name), "core%02d", c->core_id);
+	/* If not using logical core numbering, set core id */
+	if (!config_lcn) {
```
Comment (Feandil) [inline src/turbostat.c]: The rest of this file do not use ```{``` ```}``` for single line ```if```
