### PR TITLE
exec: fix a race condition when setting environment variables

### LINKED ISSUE #3041: Bug in Exec: missing environment variables in many of children processes
*   Version of collectd: 5.8.1
*   Operating system / distribution: built from source
*   Kernel version (if applicable): not applicable

## Expected behavior

All children processes should have environment variables COLLECTD_INTERVAL and COLLECTD_HOSTNAME accessible

## Actual behavior

Some of children processes are missing COLLECTD_INTERVAL and COLLECTD_HOSTNAME. Which processes are missing variables is always different.

## Steps to reproduce

Configure a number of external programs running with Exec plugin (let it be just a simple shell script echo-ing environment variables to a file) and start collectd.

## Notes
If my reading of the code is correct there is a possibility of race in [fork_child](https://github.com/collectd/collectd/blob/collectd-5.8.1/src/exec.c#L441) when setting ([1](https://github.com/collectd/collectd/blob/collectd-5.8.1/src/exec.c#L497)) and unsetting ([2](https://github.com/collectd/collectd/blob/collectd-5.8.1/src/exec.c#L541), [3](https://github.com/collectd/collectd/blob/collectd-5.8.1/src/exec.c#L565)) environment variables which is likely to be the cause.

### PR DESCRIPTION
**Pull request by mkauf**
Pass the environment as a parameter to the child process
and don't modify the environment of the parent process.

Follow-up to 0684aea7

Closes #3041

Changelog: exec: fix a race condition when setting environment variables

### CODE REVIEW

File: src/exec.c [hunk 1]
```diff
@@ -486,17 +456,42 @@ static int fork_child(program_list_t *pl, int *fd_in, int *fd_out,
...
+    size_t envp_idx;
+    for (envp_idx = 0; environ[envp_idx] != NULL && envp_idx < env_size;
+         ++envp_idx) {
+      envp[envp_idx] = environ[envp_idx];
+    }
+
+    /* Add the collectd environment variables */
+    envp[envp_idx++] = interval_buf;
+    envp[envp_idx++] = hostname_buf;
+    envp[envp_idx++] = NULL;
```
Comment (kwiatrox) [inline src/exec.c]: Minor issue: envp_idx is not used any more after that line, so increment is not necessary here.

Comment (mkauf) [reply src/exec.c]: A bot already merged this PR, I don't know how to proceed.

Comment (mrunge) [reply src/exec.c]: Submit a new PR then?
